import styles from '../../styles/LoadingScreen.module.css';
import Head from 'next/head';

const LoadingScreen = () => {
  return (
    <>
      <Head>
        <title>Discord Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/discord.ico" />
      </Head>
      <div className=" flex justify-center items-center bg-[#2f3136] text-[#b9bbbe] min-h-screen">
        <div className="h-32 w-32 relative">
          <div className={styles.box1}></div>
          <div className={styles.box2}></div>
        </div>
      </div>
    </>
  );
};

export default LoadingScreen;
