import React, { useState } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Login.module.css';
import { useRouter } from 'next/router';
import LoadingScreen from '../components/Loading/LoadingScreen';

function login() {
  const router = useRouter();
  const handleSubmit = (e) => {
    console.log('ini email', e.target.email.value);
    console.log('ini password', e.target.password.value);

    localStorage.setItem(
      'SignInUser',
      JSON.stringify({
        email: e.target.email.value,
        password: e.target.password.value,
      })
    );
    e.preventDefault();
    router.push('/channel/@me/1');
  };

  return (
    <div>
      <Head>
        <title>Discord Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/discord.ico" />
      </Head>
      <main className="bg-cover h-screen flex justify-center items-center" style={{ backgroundImage: "url('/background-discord.png')" }}>
        <div className={styles['box']}>
          <div className="w-7/12">
            <h1 className="font-bold text-2xl text-center mb-2">Welcome Back!</h1>
            <p className="text-[#a7a9ac] text-center mb-4">We're so excited to see you again!</p>
            <form onSubmit={handleSubmit}>
              <div className="flex flex-col mb-5">
                <label htmlFor="" className="text-xs font-bold text-[#afb1b5] mb-2">
                  EMAIL OR PHONE NUMBER <span className="text-red-500">*</span>
                </label>
                <input type="text" id="email" className="p-2 bg-[#202225] active:outline-none focus:outline-none rounded-sm" />
              </div>
              <div className="flex flex-col mb-5">
                <label htmlFor="" className="text-xs font-bold text-[#afb1b5] mb-2">
                  PASSWORD <span className="text-red-500">*</span>
                </label>
                <input type="text" id="password" className="p-2 bg-[#202225] active:outline-none focus:outline-none rounded-sm mb-1" />
                <p className="text-sm text-[#04a6e6]">Forgot your password?</p>
              </div>
              <button className="bg-[#5865f2] text-[#fefefe] w-full rounded text-center py-2 mb-2">Log In</button>
            </form>
            <p className="text-sm text-[#8e9196]">
              Need an account?{' '}
              <Link href="/register">
                <span className="text-[#04a6e6]">Register</span>
              </Link>
            </p>
          </div>
          <div className="w-5/12">
            <p>qrcode</p>
          </div>
        </div>
      </main>
    </div>
  );
}

export default login;
