import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Register.module.css';

function register() {
  return (
    <div>
      <Head>
        <title>Discord Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/discord.ico" />
      </Head>
      <main className="bg-cover h-screen flex justify-center items-center" style={{ backgroundImage: "url('/background-discord.png')" }}>
        <div className={styles['box']}>
          <h1 className="text-center font-bold text-2xl mb-5">Create an account</h1>
          <div className="flex flex-col mb-5">
            <label htmlFor="" className="text-xs font-bold text-[#afb1b5] mb-2">
              EMAIL
            </label>
            <input type="text" className="p-2 bg-[#202225] active:outline-none focus:outline-none rounded-sm" />
          </div>
          <div className="flex flex-col mb-5">
            <label htmlFor="" className="text-xs font-bold text-[#afb1b5] mb-2">
              USERNAME
            </label>
            <input type="text" className="p-2 bg-[#202225] active:outline-none focus:outline-none rounded-sm" />
          </div>
          <div className="flex flex-col mb-5">
            <label htmlFor="" className="text-xs font-bold text-[#afb1b5] mb-2">
              PASSWORD
            </label>
            <input type="text" className="p-2 bg-[#202225] active:outline-none focus:outline-none rounded-sm" />
          </div>
          <div className="flex flex-col mb-5">
            <label htmlFor="" className="text-xs font-bold text-[#afb1b5] mb-2">
              DATE OF BIRTH
            </label>
            <div className="flex gap-2 mb-5">
              <input type="text" className="w-4/12 p-2 bg-[#202225] active:outline-none focus:outline-none rounded-sm" placeholder="Month" />
              <input type="text" className="w-4/12 p-2 bg-[#202225] active:outline-none focus:outline-none rounded-sm" placeholder="Day" />
              <input type="text" className="w-4/12 p-2 bg-[#202225] active:outline-none focus:outline-none rounded-sm" placeholder="Year" />
            </div>
            <button className="bg-[#5865f2] text-[#fefefe] w-full rounded text-center py-2 mb-2">Continue</button>
            <Link href="/login">
              <p className="text-sm text-[#04a6e6]">Already have an account?</p>
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}

export default register;
