import React from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import UserMessage from '../../../components/UserMsg';
import { useEffect, useState } from 'react';
import LoadingScreen from '../../../components/Loading/LoadingScreen';
import BottomNavAudio from '../../../components/BottomNavAudio';
import ListUser from '../../../components/ListUser';
import SidebarChannel from '../../../components/SidebarChannel';

function MeDetail() {
  const router = useRouter();
  const { id } = router.query;
  const [AuthUser, setAuthUser] = useState();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let user = localStorage.getItem('SignInUser');
    setAuthUser(JSON.parse(localStorage.getItem('SignInUser')));
    if (!user) {
      router.push('/login');
    }
    setTimeout(() => setLoading(false), 4000);
  }, []);

  return !loading ? (
    <>
      <Head>
        <title>Discord Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/discord.ico" />
      </Head>
      <div className="h-screen w-screen flex">
        <SidebarChannel />

        {/* Sidebar Contact */}
        <div className="w-[17.5%] bg-[#2f3136] overflow-y-scroll">
          <div className=" fixed w-[inherit] bg-[#2f3136] border-b border-[#25262b] shadow-lg h-[48px] p-3 flex justify-center items-center">
            <input type="text" className="w-full rounded bg-[#202225] text-[#b9bbbe] px-2 focus:outline-none text-[14px] py-1" placeholder="Find or start a conversation" />
          </div>
          <ListUser />
          <BottomNavAudio />
        </div>
        {/* End Sidebar Contact */}
        {/* Main */}
        <div className="w-[77.2%] bg-[#36393f] overflow-y-scroll">
          {/* Default Chat nya kosong dulu */}
          <UserMessage />
        </div>
        {/* End Main */}
      </div>
    </>
  ) : (
    <LoadingScreen />
  );
}

export default MeDetail;
